# Python stubs generated by omniidl from OperationsBancaires.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "bankapp"
#
__name__ = "bankapp"
_0_bankapp = omniORB.openModule("bankapp", r"OperationsBancaires.idl")
_0_bankapp__POA = omniORB.openModule("bankapp__POA", r"OperationsBancaires.idl")


# interface OperationsBancaires
_0_bankapp._d_OperationsBancaires = (omniORB.tcInternal.tv_objref, "IDL:bankapp/OperationsBancaires:1.0", "OperationsBancaires")
omniORB.typeMapping["IDL:bankapp/OperationsBancaires:1.0"] = _0_bankapp._d_OperationsBancaires
_0_bankapp.OperationsBancaires = omniORB.newEmptyClass()
class OperationsBancaires :
    _NP_RepositoryId = _0_bankapp._d_OperationsBancaires[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_bankapp.OperationsBancaires = OperationsBancaires
_0_bankapp._tc_OperationsBancaires = omniORB.tcInternal.createTypeCode(_0_bankapp._d_OperationsBancaires)
omniORB.registerType(OperationsBancaires._NP_RepositoryId, _0_bankapp._d_OperationsBancaires, _0_bankapp._tc_OperationsBancaires)

# OperationsBancaires operations and attributes
OperationsBancaires._d_balance = ((), (omniORB.tcInternal.tv_double, ), None)
OperationsBancaires._d_depot = ((omniORB.tcInternal.tv_double, ), (), None)
OperationsBancaires._d_retrait = ((omniORB.tcInternal.tv_double, ), (), None)

# OperationsBancaires object reference
class _objref_OperationsBancaires (CORBA.Object):
    _NP_RepositoryId = OperationsBancaires._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def balance(self, *args):
        return self._obj.invoke("balance", _0_bankapp.OperationsBancaires._d_balance, args)

    def depot(self, *args):
        return self._obj.invoke("depot", _0_bankapp.OperationsBancaires._d_depot, args)

    def retrait(self, *args):
        return self._obj.invoke("retrait", _0_bankapp.OperationsBancaires._d_retrait, args)

omniORB.registerObjref(OperationsBancaires._NP_RepositoryId, _objref_OperationsBancaires)
_0_bankapp._objref_OperationsBancaires = _objref_OperationsBancaires
del OperationsBancaires, _objref_OperationsBancaires

# OperationsBancaires skeleton
__name__ = "bankapp__POA"
class OperationsBancaires (PortableServer.Servant):
    _NP_RepositoryId = _0_bankapp.OperationsBancaires._NP_RepositoryId


    _omni_op_d = {"balance": _0_bankapp.OperationsBancaires._d_balance, "depot": _0_bankapp.OperationsBancaires._d_depot, "retrait": _0_bankapp.OperationsBancaires._d_retrait}

OperationsBancaires._omni_skeleton = OperationsBancaires
_0_bankapp__POA.OperationsBancaires = OperationsBancaires
omniORB.registerSkeleton(OperationsBancaires._NP_RepositoryId, OperationsBancaires)
del OperationsBancaires
__name__ = "bankapp"

#
# End of module "bankapp"
#
__name__ = "OperationsBancaires_idl"

_exported_modules = ( "bankapp", )

# The end.
