# DO NOT EDIT THIS FILE!
#
# Python module bankapp__POA generated by omniidl

import omniORB
omniORB.updateModule("bankapp__POA")

# ** 1. Stub files contributing to this module
import OperationsBancaires_idl

# ** 2. Sub-modules

# ** 3. End
