# DO NOT EDIT THIS FILE!
#
# Python module bankapp generated by omniidl

import omniORB
omniORB.updateModule("bankapp")

# ** 1. Stub files contributing to this module
import OperationsBancaires_idl

# ** 2. Sub-modules

# ** 3. End
